# Copyright 2020 Camptocamp SA
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl)

from odoo import fields, models


class ResPartner(models.Model):
    _inherit = "res.partner"

    customer_number = fields.Char(
        help="Unique identifier of the member (customer). Generated by WIM",
        track_visibility="onchange",
        readonly=True,
    )
    swisspass_customerid = fields.Char(
        help="Unique SwissPass identifier", track_visibility="onchange"
    )
    newsletter = fields.Boolean(
        help="Member is registered to receive newsletters",
        track_visibility="onchange",
    )
