# Copyright 2020 Camptocamp SA
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl)

from odoo import fields, models


class ResPartner(models.Model):
    _inherit = "res.partner"

    customer_number = fields.Char(
        help="Unique identifier of the member (customer). Generated by WIM",
        tracking=True,
        index=True,
    )
    swisspass_customerid = fields.Char(
        help="Unique SwissPass identifier",
        tracking=True,
        readonly=True,
    )
    newsletter = fields.Boolean(
        help="Member is registered to receive newsletters",
        tracking=True,
    )
