# Copyright 2018 Camptocamp SA
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html)

import anthem


@anthem.log
def remove_all_custom_views(ctx):
    """Remove all custom views"""
    ctx.env["ir.ui.view.custom"].search([]).unlink()


@anthem.log
def remove_all_custom_exports(ctx):
    """Remove all custom exports"""

    # Before unlink all these exports,
    # you can install manually the module "base_export_manager"
    # which will add a menu: "Settings > Technical > Export Profiles".
    # With that, for a future usage,
    # you can get an export of all export you will delete.
    ctx.env["ir.exports"].search([]).unlink()


@anthem.log
def disable_automated_actions(ctx):
    """Disable all automated actions."""
    base_automation = ctx.env["ir.module.module"].search(
        [("name", "=", "base_automation")]
    )
    if base_automation.state == "installed":
        ctx.env["base.automation"].search([]).write({"active": False})


@anthem.log
def disable_studio_modifications(ctx):
    """Disable Odoo Studio views."""
    query = """
        UPDATE ir_ui_view
        SET active=false
        WHERE id IN (
            SELECT res_id FROM ir_model_data
            WHERE module='studio_customization'
            AND model='ir.ui.view'
        );
    """
    ctx.env.cr.execute(query)


@anthem.log
def disable_upgrade_test_views(ctx):
    """Disable views generated by the Odoo S.A. migration in 'test' mode.

    There are two views: a banner and a ribbon.
    """
    xml_ids = [
        "__upgrade__.upg_test_banner",
        "__upgrade__.upg_test_ribbon",
    ]
    view_ids = []
    for xml_id in xml_ids:
        view = ctx.env.ref(xml_id, raise_if_not_found=False)
        if view:
            view_ids.append(view.id)
    if view_ids:
        query = """
            UPDATE ir_ui_view
            SET active=false, active_backup=false
            WHERE id IN %s
        """
        ctx.env.cr.execute(query, (tuple(view_ids),))


@anthem.log
def pre(ctx):
    """PRE: migration"""
    remove_all_custom_views(ctx)
    remove_all_custom_exports(ctx)
    disable_automated_actions(ctx)
    disable_studio_modifications(ctx)
    disable_upgrade_test_views(ctx)
